language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

env:
  - BEHAT_PARAMS="formatter[name]=pretty"

install:
  - sudo apt-get install parallel

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - ./tools/travis/selenium.sh start

script:
  - find features/ -iname '*.feature' | parallel --gnu ./bin/behat

after_script:
  - ./tools/travis/selenium.sh stop
