parameters:
    argument_resolver.services:
          GuzzleHttp\ClientInterface: http_client

services:
    http_client:
        # switch to http_client.guzzle to make real http requests,
        # or to http_client.recorder to make real http requests and record them for http_client.filesystem
        alias: http_client.filesystem

    http_client.guzzle:
        class: GuzzleHttp\Client

    http_client.filesystem:
        class: Http\FilesystemClient
        arguments:
            - @http_client.filesystem.file_locator

    http_client.recorder:
        class: Http\RecorderClient
        arguments:
            - @http_client.guzzle
            - @http_client.filesystem.file_locator

    http_client.filesystem.file_locator:
        class: Http\ResponseFileLocator

    argument_resolver:
        class: Context\Argument\ConfigurableArgumentResolver
        arguments:
            - @service_container
            - %argument_resolver.services%
        tags:
            - { name: context.argument_resolver }


